"""add_chat_escalations

Revision ID: 0ecbc808eae0
Revises: f6dc36ecccd3
Create Date: 2026-03-17 12:19:11.024599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecbc808eae0'
down_revision: Union[str, None] = 'f6dc36ecccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_escalations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('auto_escalated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'responded', 'closed', name='escalationstatus'), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=True),
    sa.Column('psychologist_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_escalations_user_id'), 'chat_escalations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_escalations_user_id'), table_name='chat_escalations')
    op.drop_table('chat_escalations')
    # ### end Alembic commands ###
